### ISSUE TITLE
error booting from tape UTX/32 2.1A or UTX/32 2.1B

### ISSUE THREAD

**Issue by neozeed** [AZBevier/sims#1]
when trying the '1' version of either UTX I get this:

```
MT Boot dev/unit 1000

Booting from TAPE
File is COFF format
-> section (.bss) size (161552) clearing at (0xc0430)
-> section (.text) size (684640) loading at (0x1200)
-> section (.data) size (98256) loading at (0xa8460)

I/O error occurred

[][][][][][][][][][] HALT [][][][][][][][][][]
PSD1 a22002e4 PSD2 00000000 TRAPME 0000
GPR[0] 00000000 GPR[1] 00000006
GPR[2] 00200854 GPR[3] 00000000
GPR[4] 00008080 GPR[5] 001ffb4c
GPR[6] 000f7b40 GPR[7] 00000072
BR[0] 00000000 BR[1] 0020010c
BR[2] 001ffe60 BR[3] 00200000
BR[4] 00ffffff BR[5] 00ffffff
BR[6] 00ffffff BR[7] 00ffffff
[][][][][][][][][][] HALT [][][][][][][][][][]

```

Ive tried the sel32.exe in the git archive, and trying to recompile myself.  I see the COFF header like it's loading something then it crashes. I guess I'm missing something?  

As a teen I grew up in the Plantation/Miami area in the 90's and surprisingly never knew Gould was a thing, nor that there was such a UNIX vendor just down the road.  Thanks so much for your work in bringing this back to life!

**Comment by AZBevier** [comment]
neozeed,

Thanks for trying the SEL32 simulator.  I have been on vacation for the last 5 weeks and am on my way home.  In a couple days I will be able to help you.  Please provide the file name you are trying and location.  Also which version of SEL32 you are using and archive.

Thanks again,

Jim

From: neozeed 
Sent: Thursday, August 19, 2021 4:59 AM
To: AZBevier/sims 
Cc: Subscribed 
Subject: [AZBevier/sims] error booting from tape UTX/32 2.1A or UTX/32 2.1B (#1)

when trying the '1' version of either UTX I get this:

MT Boot dev/unit 1000

Booting from TAPE
File is COFF format
-> section (.bss) size (161552) clearing at (0xc0430)
-> section (.text) size (684640) loading at (0x1200)
-> section (.data) size (98256) loading at (0xa8460)

I/O error occurred

[][][][][][][][][][] HALT [][][][][][][][][][]
PSD1 a22002e4 PSD2 00000000 TRAPME 0000
GPR[0] 00000000 GPR[1] 00000006
GPR[2] 00200854 GPR[3] 00000000
GPR[4] 00008080 GPR[5] 001ffb4c
GPR[6] 000f7b40 GPR[7] 00000072
BR[0] 00000000 BR[1] 0020010c
BR[2] 001ffe60 BR[3] 00200000
BR[4] 00ffffff BR[5] 00ffffff
BR[6] 00ffffff BR[7] 00ffffff
[][][][][][][][][][] HALT [][][][][][][][][][]

Ive tried the sel32.exe in the git archive, and trying to recompile myself. I see the COFF header like it's loading something then it crashes. I guess I'm missing something?

As a teen I grew up in the Plantation/Miami area in the 90's and surprisingly never knew Gould was a thing, nor that there was such a UNIX vendor just down the road. Thanks so much for your work in bringing this back to life!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rcornwell** [comment]
Hi Jim,

   I tried this on my repo and it has a problem. If you go back to your previous commit to my repo it works. So something in the last commit broke it.

Rich

**Comment by neozeed** [comment]
Hey Jim enjoy the vacation, it's no big deal I can totally work.  Rich has pointed to some some issue with the tape booting and Ill look there.  I was able to build a kernel from source and surprisingly it booted!  so that's a cool plus too!

**Comment by neozeed** [comment]
I did a couple tests to see what Jim had said, and yes the older version fbf62937ef8033b1cec052051b7a12647aa51bb3 does work

https://github.com/rcornwell/sims/commit/fbf62937ef8033b1cec052051b7a12647aa51bb3

This is the later version:
0ed44354b562229de001e4c8b855b7cdebfd88cf

```
C:\proj\sel32\ed\sims-0ed44354b562229de001e4c8b855b7cdebfd88cf>sel32.exe utxtest1a.ini

SEL-32 simulator V4.0-0 Current        git commit id: 0ed44354
C:/proj/sel32/ed/sims-0ed44354b562229de001e4c8b855b7cdebfd88cf/utxtest1a.ini-2> set debug -n sel.log
Debug output to "sel.log"
C:/proj/sel32/ed/sims-0ed44354b562229de001e4c8b855b7cdebfd88cf/utxtest1a.ini-67> at ec tap:tap0
Command not allowed
C:/proj/sel32/ed/sims-0ed44354b562229de001e4c8b855b7cdebfd88cf/utxtest1a.ini-72> set coml dev=7ec0
Invalid argument
C:/proj/sel32/ed/sims-0ed44354b562229de001e4c8b855b7cdebfd88cf/utxtest1a.ini-84> at comc 4747
Listening on port 4747
C:/proj/sel32/ed/sims-0ed44354b562229de001e4c8b855b7cdebfd88cf/utxtest1a.ini-120> at mta0 utx21a1.tap
MTA0: Tape Image 'utx21a1.tap' scanned as SIMH format
C:/proj/sel32/ed/sims-0ed44354b562229de001e4c8b855b7cdebfd88cf/utxtest1a.ini-144> at dma0 utx21a0disk
DMA0: creating new file
Disk 9346 cyl 823 hds 19 sec 16 ssiz 1024 capacity 250192
Disk attach ftell failed s=000000
Initialize disk? [Y]
.........
Disk 9346 has 337 (823) cyl, 13 (19) hds, 10 (16) sec
writing to vmap sec 3cdb0 (249264) bytes f36c000 (255246336)
writing to dmap sec 3d14f (250191) f453c00 (256195584) dmap to 3cda0 (249248) f368000 (255229952)
writing to fmap sec 3cd90 (249232) bytes f364000 (255213568)
writing to umap sec 3cd80 (249216) bytes f360000 (255197184)
disk_label WTL daddr@daddr 0003cda0 -> 00000000
disk_format WTL vaddr@daddr 0003cdb0 -> 0003cda0
UDP Attach 9346 cyl 823 hds 19 spt 16 spc 304 cap sec 250192 cap bytes 256196608
UDP File utx21a0disk attached to 9346 with labels
MT Boot dev/unit 1000

Booting from TAPE
File is COFF format
-> section (.bss) size (159872) clearing at (0xbe700)
-> section (.text) size (678112) loading at (0x1200)
-> section (.data) size (97312) loading at (0xa6ae0)

I/O error occurred

[][][][][][][][][][] HALT [][][][][][][][][][]
PSD1 a22002e4 PSD2 00000000 TRAPME 0000
GPR[0] 00000000 GPR[1] 00000006
GPR[2] 00200854 GPR[3] 00000000
GPR[4] 00008080 GPR[5] 001ffb4c
GPR[6] 000f5780 GPR[7] 00000042
BR[0] 00000000 BR[1] 0020010c
BR[2] 001ffe60 BR[3] 00200000
BR[4] 00ffffff BR[5] 00ffffff
BR[6] 00ffffff BR[7] 00ffffff
[][][][][][][][][][] HALT [][][][][][][][][][]
```


```
C:\proj\sel32\fb\sims-fbf62937ef8033b1cec052051b7a12647aa51bb3>scp.exe utxtest1a.ini

SEL-32 simulator V4.0-0 Current        git commit id: fbf62937
C:/proj/sel32/fb/sims-fbf62937ef8033b1cec052051b7a12647aa51bb3/utxtest1a.ini-2> set debug -n sel.log
Debug output to "sel.log"
C:/proj/sel32/fb/sims-fbf62937ef8033b1cec052051b7a12647aa51bb3/utxtest1a.ini-67> at ec tap:tap0
Command not allowed
C:/proj/sel32/fb/sims-fbf62937ef8033b1cec052051b7a12647aa51bb3/utxtest1a.ini-72> set coml dev=7ec0
Invalid argument
C:/proj/sel32/fb/sims-fbf62937ef8033b1cec052051b7a12647aa51bb3/utxtest1a.ini-84> at comc 4747
Listening on port 4747
C:/proj/sel32/fb/sims-fbf62937ef8033b1cec052051b7a12647aa51bb3/utxtest1a.ini-120> at mta0 utx21a1.tap
MTA0: Tape Image 'utx21a1.tap' scanned as SIMH format
C:/proj/sel32/fb/sims-fbf62937ef8033b1cec052051b7a12647aa51bb3/utxtest1a.ini-144> at dma0 utx21a0disk
DMA0: creating new file
Disk 9346 cyl 823 hds 19 sec 16 ssiz 1024 capacity 250192
Disk attach ftell failed s=000000
Initialize disk? [Y]
.........
Disk 9346 has 337 (823) cyl, 13 (19) hds, 10 (16) sec
writing to vmap sec 3cdb0 (249264) bytes f36c000 (255246336)
writing to dmap sec 3d14f (250191) f453c00 (256195584) dmap to 3cda0 (249248) f368000 (255229952)
writing to fmap sec 3cd90 (249232) bytes f364000 (255213568)
writing to umap sec 3cd80 (249216) bytes f360000 (255197184)
disk_label WTL daddr@daddr 0003cda0 -> 00000000
disk_format WTL vaddr@daddr 0003cdb0 -> 0003cda0
UDP Attach 9346 cyl 823 hds 19 spt 16 spc 304 cap sec 250192 cap bytes 256196608
UDP File utx21a0disk attached to 9346 with labels
MT Boot dev/unit 1000

Booting from TAPE
File is COFF format
-> section (.bss) size (159872) clearing at (0xbe700)
-> section (.text) size (678112) loading at (0x1200)
-> section (.data) size (97312) loading at (0xa6ae0)

File is COFF format
-> section (memdisk) size (1507328) loading at (0x290000)

Start 0x1200

UTX/32 2.1A (exp) #1: Fri Jun 24 07:32:20 CDT 1988
    root@mycroft:/usr.POWERNODE/src/src/sys/obj

V6 CPUIPU(P) configuration (IPU not present)
top of system = 0x400000
real mem = 8388608
End of kernel map 0x1680c8
avail memory = 5922816
using 56 buffers containing 57344 bytes of memory
using 56 mirror buffer headers
ioi: channel iop0 at 7e00 online
ioi: channel dc0 at 800 online
ioi: channel dc1 at c00 not present, dci cc=2
ioi: channel dc2 at 400 not present, dci cc=2
ioi: channel tc0 at 1000 online
ioi: channel tc1 at 1800 not present, dci cc=2
 -- CHECK AND RESET THE DATE!
SYSTEM SWAPPING IS DISABLED
** /dev/md0a
** Last Mounted on /
** Root file system
** Phase 1 - Check Blocks and Sizes
** Phase 2 - Check Pathnames
** Phase 3 - Check Connectivity
** Phase 4 - Check Reference Counts
** Phase 5 - Check Cyl groups
400 files, 1286 used, 73 free (9 frags, 8 blocks, 0.7% fragmentation)
#

```

And here we go with the older version booted to tape.

I used Visual C++ 2010, and just a simple thing to build the executable as I'm too impatient:

```
cl -U__STRICT_ANSI__  -I. -DHAVE_NTDDDISK_H -DSIM_COMPILER="GCC Version: 5.1.0" -DSIM_BUILD_TOOL=simh-makefile -I .   ./SEL32/sel32_cpu.c ./SEL32/sel32_sys.c ./SEL32/sel32_chan.c ./SEL32/sel32_iop.c ./SEL32/sel32_com.c ./SEL32/sel32_con.c ./SEL32/sel32_clk.c ./SEL32/sel32_mt.c ./SEL32/sel32_lpr.c ./SEL32/sel32_scfi.c ./SEL32/sel32_fltpt.c ./SEL32/sel32_disk.c ./SEL32/sel32_hsdp.c ./SEL32/sel32_mfp.c ./SEL32/sel32_scsi.c ./SEL32/sel32_ec.c ./scp.c ./sim_console.c ./sim_fio.c ./sim_timer.c ./sim_sock.c ./sim_tmxr.c ./sim_ether.c ./sim_tape.c ./sim_disk.c ./sim_serial.c ./sim_video.c ./sim_imd.c ./sim_card.c -I ./SEL32 -DSEL32  -DUSE_SHARED 

cl /c /DHAVE_SLIRP_NETWORK sim_ether.c
cl *.obj /Fesel32.exe  wsock32.lib winmm.lib advapi32.lib
```

**Comment by neozeed** [comment]
d9bcafc2b18bc47a8eadbf9bacfb305b77346f96 let's me boot from tape FWIW

**Comment by AZBevier** [comment]
neozeed,

Here is a work in progress sel32_mt.c file that fixes the halt issue with UTX21a & UTX21b installations.  I will push out the changes in the next day or so after some more testing.  It seems I broke skip file processing when trying to get MPX3X to work with master SDT tapes.

Jim

**Comment by neozeed** [comment]
super cool! hope you had a great vacation!

**Comment by AZBevier** [comment]
sims archive now updated with latest code to fix this issue.  Please try the revised version.  Also use the load21a.ini and load21b.ini command files to build the test disks.

**Comment by AZBevier** [comment]
Forgot to Close.....

**Comment by neozeed** [comment]
oh yeah forgot to mention I installed from tape fine! thanks

**Comment by AZBevier** [comment]
neozeed,

I have a new nbc environment for you to play with.  It now builds all of the necessary files to build linux, mpx1x, and mpx3x files.

Jim
